model: yolo12n.yaml
data: configs/datasets/armor.yaml
epochs: 500
patience: 60
batch: -1
imgsz: 192
device: 0
workers: 4
project: runs/armor
name: armor_from_scratch
pretrained: false
optimizer: auto
seed: 2026
deterministic: true
amp: true
cache: false
close_mosaic: 10
hsv_h: 0.01
hsv_s: 0.35
hsv_v: 0.4
translate: 0.1
scale: 0.4
fliplr: 0.5
mosaic: 0.8
mixup: 0.05
